### ISSUE TITLE
Add key inside the object

### ISSUE THREAD

**Issue by eznix86** [just1and0/object-to-array-convert#1]
The code is super nice, but we lose the key, once the value is loaded.

Can you make an update so that we can get the key also?

**Comment by just1and0** [comment]
Thanks for using the project and also bringing this up. I'd be sure to add that in the next update.

**Comment by just1and0** [comment]
Hey @theArtechnology 

Please update the project to the latest version. 
The new update adds an **object_key** field after using the O2A API, which contains the object key.
